import '../styles/globals.scss'
import Head from 'next/head'
import Navbar from '../components/navbar'
import Footer from '../components/footer'
// import { useState } from 'react'

function MyApp({ Component, pageProps }) {
  // const [isLoading, setIsLoading] = useState(true);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      {/* {isLoading && <div className="loading">
        <span className="loader"></span>
      </div>} */}

      <Navbar />
      <Component {...pageProps} />
      <Footer />
    </div>

  )
}

export default MyApp
